In [1]:
import numpy as np
import math 
n = 100
N = 10000
Bn = 0
for i in range(N):
	Bn = Bn + (i+1)**n/math.factorial(i+1)
Bn = Bn/math.e
print(Bn)

4.758539127676484e+115


In [3]:
def rng(m=2**32, a=1103515245, c=12345):
    rng.current = (a * rng.current + c) % m
    return rng.current / m
def K_gen(Bn,n):
	x = rng()
	k = 1
	f = 0
	while f < x:
		f += k**n/(math.factorial(k)*math.e*Bn)
		k+=1
		if k > 2*n:
			f = x
	return k-1
def C_gen(K):
	x = rng()
	f = 0
	i = 0
	while f < x:
		f += 1/K
		i +=1
	return i-1
def Generator(n , Bn):
	K = K_gen(Bn,n)
	C = np.empty(n)
	for i in range(n):
		C[i] = C_gen(K)
	return C
rng.current = 1
C = Generator(n,Bn)
Uniq = np.unique(C,axis = 0)
C1 = np.arange(n)
for i in Uniq:
	mask = i == C
	print(C1[mask]+1, "<-множество ", int(i+1))

[74] <-множество  1
[ 9 10 43 78] <-множество  2
[ 44  75 100] <-множество  3
[12 65 67 83 93] <-множество  4
[ 2 23 24 52 58] <-множество  5
[11 36 69 71 73 89] <-множество  6
[41 60 68] <-множество  7
[26 64] <-множество  8
[22 28 55 62] <-множество  9
[33 77 90 98] <-множество  10
[49 80] <-множество  11
[39] <-множество  12
[25 61] <-множество  13
[14 42 45 50 95] <-множество  14
[51 56 59 87] <-множество  15
[63] <-множество  16
[ 1  5 21 38] <-множество  17
[ 7 54 81] <-множество  18
[37 82 84 85] <-множество  19
[13 27 40 47 72 79] <-множество  20
[ 8 66 97] <-множество  21
[ 3 15 76] <-множество  22
[35] <-множество  23
[ 6 17 88] <-множество  24
[16 18 19 29 34 46 48 53 91 96] <-множество  25
[20 94 99] <-множество  26
[31 32 70 86] <-множество  27
[ 4 30 57 92] <-множество  28
